development:
  sessions:
    default:
      database: restinme_development
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: restinme_test
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      database: restinme_production
      hosts:
        - localhost:27017
