development:
  sessions:
    default:
      database: authk_development
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: authk_test
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      database: authk_production
      hosts:
        - localhost:27017
