development:
  sessions:
    default:
      database: authentik_development
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: authentik_test
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      database: authentik_production
      hosts:
        - localhost:27017
