defaults: &DEFAULTS
  adapter: postgresql
  encoding: 'utf8'
  pool: 10
  timeout: 5000

development:
  <<: *DEFAULTS
  database: api_tie_development

test:
  <<: *DEFAULTS
  database: api_tie_test
  pool: 5
  timeout: 1000

production:
  <<: *DEFAULTS
  database: api_tie
